const $=s=>document.querySelector(s);let state=JSON.parse(localStorage.getItem('flightSchoolFlat')||'{"mission":0,"xp":0,"rank":"SKY SCOUT"}');let current=[],idx=0,lives=3,locked=false;const missions=window.FLIGHT_BANK;
function save(){localStorage.setItem('flightSchoolFlat',JSON.stringify(state))}function shuffle(a){return [...a].sort(()=>Math.random()-.5)}function sound(type){try{let c=new (window.AudioContext||window.webkitAudioContext)(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.type=type==='bad'?'sawtooth':'triangle';o.frequency.value=type==='bad'?150:type==='win'?880:620;g.gain.setValueAtTime(.05,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.18);o.start();o.stop(c.currentTime+.2)}catch(e){}}
function startMission(){lives=3;idx=0;locked=false;let m=missions[state.mission]||missions[0];current=shuffle(m.bank).slice(0,m.count);$('#missionTitle').textContent=m.title;$('#skillLabel').textContent=m.skill;render();updateHud()}
function updateHud(){let pct=Math.round((idx/15)*100);$('#progressBar').style.setProperty('--w',pct+'%');$('#bird').style.setProperty('--progress',pct);$('#missionStat').textContent=`MISSION ${state.mission+1}/${missions.length}`;$('#lifeStat').textContent='❤ '.repeat(lives).trim();$('#xpStat').textContent=`XP ${state.xp}`;$('#rank').textContent=state.xp>650?'CAMP ACE':state.xp>300?'WING LEADER':'SKY SCOUT'}
function render(){updateHud();$('#feedback').textContent='';let q=current[idx];if(!q){win();return}$('#prompt').textContent=q.prompt;let area=$('#answerArea');area.innerHTML='';if((missions[state.mission].mode==='input')&&!q.choices){area.className='input-row';let input=document.createElement('input');input.className='game-input';input.inputMode='numeric';input.setAttribute('aria-label','Answer');let btn=document.createElement('button');btn.className='submit';btn.textContent='CHECK';btn.onclick=()=>check(input.value,q.answer,btn);input.addEventListener('keydown',e=>{if(e.key==='Enter')check(input.value,q.answer,btn)});area.append(input,btn);input.focus()}else{area.className='answers';let choices=q.choices||makeChoices(q.answer);shuffle(choices).forEach(c=>{let b=document.createElement('button');b.className='answer';b.textContent=c;b.onclick=()=>check(c,q.answer,b);area.appendChild(b)})}}
function makeChoices(ans){let n=Number(ans);if(Number.isNaN(n))return [ans];let s=new Set([String(ans)]);while(s.size<4){let x=n+Math.floor(Math.random()*17)-8;if(x>=0)s.add(String(x))}return [...s]}
function check(val,ans,el){if(locked)return;locked=true;let ok=String(val).trim()===String(ans).trim();if(ok){sound('good');state.xp+=10;save();if(el)el.classList.add('good');$('#feedback').textContent='CLEAR!';setTimeout(()=>{idx++;locked=false;render()},520)}else{sound('bad');lives--;if(el)el.classList.add('bad');$('#feedback').textContent=lives>0?'TRY THE NEXT ONE.':'MISSION RESET.';setTimeout(()=>{locked=false;lives>0?(idx++,render()):startMission()},760)}}
function win(){sound('win');state.xp+=50;state.mission=Math.min(state.mission+1,missions.length-1);save();$('#prompt').textContent='BADGE EARNED! NEXT MISSION LAUNCHING.';$('#answerArea').innerHTML='';$('#feedback').textContent='KEEP FLYING.';updateHud();setTimeout(()=>startMission(),1500)}
startMission();
