(function(){
  const TOTAL_PER_MISSION = 15;
  let missionIndex = 0, qNum = 0, lives = 3, xp = 0, current, lock=false;
  const $ = id => document.getElementById(id);
  const scene=$('scene'), falcon=$('falcon'), activity=$('activity'), prompt=$('prompt'), feedback=$('feedback'), overlay=$('overlay');
  const save = () => localStorage.setItem('flightSchoolProgress', JSON.stringify({missionIndex, xp, badges:[...new Set((JSON.parse(localStorage.getItem('flightSchoolProgress')||'{}').badges||[]))]}));
  function audio(freq=520,dur=.08,type='sine'){try{const ctx=new (window.AudioContext||window.webkitAudioContext)();const o=ctx.createOscillator();const g=ctx.createGain();o.type=type;o.frequency.value=freq;o.connect(g);g.connect(ctx.destination);g.gain.setValueAtTime(.0001,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.12,ctx.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+dur);o.start();o.stop(ctx.currentTime+dur+.02)}catch(e){}}
  function setHud(){const m=MISSIONS[missionIndex];$('missionPill').textContent=`MISSION ${missionIndex+1}/${MISSIONS.length}`;$('livesPill').textContent='♥ '.repeat(lives).trim();$('xpPill').textContent=`XP ${xp}`;$('missionTitle').textContent=m.name;$('progressFill').style.width=`${(qNum/TOTAL_PER_MISSION)*100}%`;falcon.style.setProperty('--x', `${Math.min(72, qNum/TOTAL_PER_MISSION*72)}vw`);falcon.style.transform=`translateX(${Math.min(72, qNum/TOTAL_PER_MISSION*72)}vw)`;}
  function startMission(){lives=3;qNum=0;scene.className=`scene ${MISSIONS[missionIndex].scene}`;overlay.classList.remove('show');feedback.textContent='';setHud();nextQuestion();}
  function nextQuestion(){lock=false;const m=MISSIONS[missionIndex];scene.className=`scene ${m.scene}`;current=m.make();current.type=current.type||m.type;const boss = qNum===4 || qNum===9 || qNum===14;$('playCard').classList.toggle('boss',boss);$('bossTag').textContent = boss ? (qNum===14?`FINAL: ${m.boss}`:'BOSS') : '';prompt.textContent = boss ? `${m.boss}: ${current.prompt}` : current.prompt;render(current,m,boss);setHud();}
  function render(q,m,boss){activity.innerHTML=''; if(q.type==='line'||m.type==='line') return renderLine(q); if(q.type==='clock'||m.type==='clock') return renderClock(q); if(m.type==='blocks') return renderBlocks(q); if(m.type==='tiles') return renderTiles(q); if(m.type==='perches'||m.type==='nests') return renderPerches(q); return renderChoices(q,m.type==='clouds');}
  function renderChoices(q,clouds=false){const wrap=document.createElement('div');wrap.className='choices '+(clouds?'cloud-choices':'');(q.choices||[]).forEach(c=>wrap.appendChild(btn(c,()=>answer(c))));activity.appendChild(wrap);}
  function renderPerches(q){const wrap=document.createElement('div');wrap.className='perch-choices';q.choices.forEach(c=>{const b=document.createElement('button');b.className='perch';b.textContent=c;b.onclick=()=>answer(c);wrap.appendChild(b)});activity.appendChild(wrap);}
  function renderBlocks(q){const wrap=document.createElement('div');wrap.className='block-builder';for(let i=0;i<(q.hundreds||0);i++)wrap.appendChild(block('100','hundred'));for(let i=0;i<(q.tens||0);i++)wrap.appendChild(block('10','ten'));for(let i=0;i<(q.ones||0);i++)wrap.appendChild(block('1','one'));const choices=document.createElement('div');choices.className='choices';q.choices.forEach(c=>choices.appendChild(btn(c,()=>answer(c))));activity.append(wrap,choices);}
  function renderTiles(q){const grid=document.createElement('div');grid.className='tile-grid';grid.style.gridTemplateColumns=`repeat(${Math.min(q.cols||4,10)},38px)`;for(let i=0;i<Math.min((q.rows||3)*(q.cols||4),80);i++){const t=document.createElement('div');t.className='tile';grid.appendChild(t)}const choices=document.createElement('div');choices.className='choices';q.choices.forEach(c=>choices.appendChild(btn(c,()=>answer(c))));activity.append(grid,choices);}
  function renderLine(q){const wrap=document.createElement('div');wrap.className='number-line';const track=document.createElement('div');track.className='line-track';for(let i=0;i<=q.den;i++){const tick=document.createElement('div');tick.className='tick';tick.style.left=`${i/q.den*100}%`;const b=document.createElement('button');b.textContent=i===0?'0':i===q.den?'1':`${i}/${q.den}`;b.onclick=()=>answer(i/q.den);tick.appendChild(b);track.appendChild(tick)}wrap.appendChild(track);activity.appendChild(wrap);}
  function renderClock(q){const wrap=document.createElement('div');wrap.className='choices';q.choices.forEach(label=>{const card=document.createElement('button');card.className='choice';card.innerHTML=clockSvg(label);card.onclick=()=>answer(label);wrap.appendChild(card)});activity.appendChild(wrap);}
  function clockSvg(label){const [h,m]=label.split(':').map(Number);const minAng=m*6-90;const hourAng=(h%12)*30+m*.5-90;return `<div class="clock-face"><span class="hand minute" style="transform:rotate(${minAng}deg)"></span><span class="hand hour" style="transform:rotate(${hourAng}deg)"></span></div>`;}
  function block(txt,cls){const d=document.createElement('div');d.className='block '+cls;d.textContent=txt;return d;}
  function btn(text,fn){const b=document.createElement('button');b.className='choice';b.textContent=text;b.onclick=fn;return b;}
  function answer(value){if(lock)return;lock=true;const ok = String(value)===String(current.answer) || Math.abs(Number(value)-Number(current.answer))<0.001;[...activity.querySelectorAll('button')].forEach(b=>{if(String(b.textContent).trim()===String(current.answer))b.classList.add('correct')});if(ok){audio(660,.07,'triangle');setTimeout(()=>audio(920,.08,'triangle'),70);xp+=10;feedback.textContent = qNum===14 ? 'MISSION CLEAR!' : 'NICE FLIGHT!';falcon.classList.remove('hit');falcon.classList.add('boost');qNum++;setHud();setTimeout(()=>falcon.classList.remove('boost'),520);setTimeout(()=>{qNum>=TOTAL_PER_MISSION?completeMission():nextQuestion()},780);}else{audio(150,.16,'sawtooth');lives--;feedback.textContent='TRY AGAIN';falcon.classList.add('hit');setHud();setTimeout(()=>falcon.classList.remove('hit'),420);setTimeout(()=>{if(lives<=0)restartMission();else lock=false;feedback.textContent=''},800)}}
  function completeMission(){const prog=JSON.parse(localStorage.getItem('flightSchoolProgress')||'{}');prog.badges=[...new Set([...(prog.badges||[]),MISSIONS[missionIndex].badge])];prog.xp=xp;prog.missionIndex=Math.max(prog.missionIndex||0,missionIndex+1);localStorage.setItem('flightSchoolProgress',JSON.stringify(prog));audio(720,.1,'triangle');setTimeout(()=>audio(960,.12,'triangle'),110);setTimeout(()=>audio(1200,.15,'triangle'),240);overlay.classList.add('show');overlay.querySelector('.modal').innerHTML=`<h2>${MISSIONS[missionIndex].badge}</h2><p>BADGE EARNED</p><div class="badge-wall">${prog.badges.map(b=>`<span class="badge">${b}</span>`).join('')}</div><button id="nextMission">KEEP FLYING</button><a href="index.html">CAMP</a>`;document.getElementById('nextMission').onclick=()=>{missionIndex++; if(missionIndex>=MISSIONS.length){finishGame()} else startMission();};}
  function restartMission(){overlay.classList.add('show');overlay.querySelector('.modal').innerHTML=`<h2>MISSION RESET</h2><p>TAKE A BREATH. TRY THE ZONE AGAIN.</p><button id="retryMission">RETRY</button><a href="index.html">CAMP</a>`;document.getElementById('retryMission').onclick=startMission;}
  function finishGame(){overlay.classList.add('show');overlay.querySelector('.modal').innerHTML=`<h2>SKY CHAMPION</h2><p>YOU CLEARED FLIGHT SCHOOL.</p><a href="index.html">BACK TO CAMP</a>`;}
  document.getElementById('startBtn').onclick=()=>{audio(520,.08,'triangle');startMission();};
})();
